language: java
jdk:
  - openjdk11
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo.
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту, если сборка упала.
notifications:
  email:
    recipients:
      - teaching-light@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="40d48b74-734a-4be6-8a01-926911a841c8"